language: rust

rust:
  - stable
  - beta
  - nightly

cache:
  - cargo

os:
  - linux

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
    - RUST_BACKTRACE=1

before_script:
  - |
    rustup component add rustfmt-preview
    if [[ "$TRAVIS_RUST_VERSION" == nightly ]]
    then
      rustup component add clippy-preview
    fi

script:
  - cargo test --verbose
  - |
    if [[ "$TRAVIS_RUST_VERSION" == nightly ]]
    then
      cargo clippy --all --tests
    fi
