[package]
name = "opai-rs"
version = "0.1.0"
authors = ["Evgeny Kurnevsky <kurnevsky@gmail.com>"]
license = "AGPL-3.0+"
description = "Open Points Artificial Intelligence"

[dependencies]
rand = "*"
time = "*"
log = "*"
log4rs = { version = "*", features = ["toml"] }
num_cpus = "*"
toml = "*"
crossbeam = "*"
rayon = "*"
clippy = { version = "*", optional = true }
tar = "*"
clap = "*"
itertools = "*"

[dev-dependencies]
quickcheck = "*"

[features]
default = ["dsu"]
dsu = []
bench = []

[profile.dev]
opt-level = 0
lto = false
debug = true
panic = "unwind"

[profile.bench]
opt-level = 3
lto = true
debug = false
panic = "abort"

[profile.release]
opt-level = 3
lto = true
debug = false
panic = "abort"
