[package]
name = "opai-rs"
version = "0.1.0"
authors = ["Kurnevsky Evgeny <kurnevsky@gmail.com>"]
license = "AGPL-3.0+"

[dependencies]
rand = "*"
time = "*"
log = "*"
log4rs = { version = "*", features = ["toml"] }
num_cpus = "*"
rustc-serialize = "*"
toml = "*"
crossbeam = "*"
rayon = "*"
clippy = { version = "*", optional = true }
tar = "*"

[dev-dependencies]
quickcheck = "*"

[profile.dev]
opt-level = 0
lto = false
debug = true
panic = "unwind"

[profile.release]
opt-level = 3
lto = true
debug = false
panic = "abort"
