[appenders.all]
kind = "file"
path = "log/all.log"
pattern = "%d{%FT%T.%f%z} [%t] %m"

[appenders.uct]
kind = "file"
path = "log/uct.log"
pattern = "%d{%FT%T.%f%z} %m"

[appenders.minimax]
kind = "file"
path = "log/minimax.log"
pattern = "%d{%FT%T.%f%z} %m"

[appenders.bot]
kind = "file"
path = "log/bot.log"
pattern = "%d{%FT%T.%f%z} %m"

[appenders.config]
kind = "file"
path = "log/config.log"
pattern = "%d{%FT%T.%f%z} %m"

[appenders.patterns]
kind = "file"
path = "log/patterns.log"
pattern = "%d{%FT%T.%f%z} %m"

[loggers.uct]
level = "debug"
appenders = ["uct", "all"]

[loggers.minimax]
level = "debug"
appenders = ["minimax", "all"]

[loggers.bot]
level = "debug"
appenders = ["bot", "all"]

[loggers.config]
level = "debug"
appenders = ["config", "all"]

[loggers.patterns]
level = "debug"
appenders = ["patterns", "all"]
