[appender.all]
kind = "file"
path = "log/all.log"
pattern = "%d [%t] %m"

[appender.uct]
kind = "file"
path = "log/uct.log"
pattern = "%d [%t] %m"

[appender.bot]
kind = "file"
path = "log/bot.log"
pattern = "%d [%t] %m"

[[logger]]
name = "uct"
level = "debug"
appenders = ["uct", "all"]

[[logger]]
name = "bot"
level = "debug"
appenders = ["bot", "all"]
