[appender.all]
kind = "file"
path = "log/all.log"
pattern = "%d [%t] %m"

[appender.uct]
kind = "file"
path = "log/uct.log"
pattern = "%d [%t] %m"

[[logger]]
name = "uct"
level = "info"
appenders = ["uct", "all"]
