[appender.all]
kind = "file"
path = "log/all.log"
pattern = "%d{%FT%T.%f%z} [%t] %m"

[appender.uct]
kind = "file"
path = "log/uct.log"
pattern = "%d{%FT%T.%f%z} %m"

[appender.minimax]
kind = "file"
path = "log/minimax.log"
pattern = "%d{%FT%T.%f%z} %m"

[appender.bot]
kind = "file"
path = "log/bot.log"
pattern = "%d{%FT%T.%f%z} %m"

[appender.config]
kind = "file"
path = "log/config.log"
pattern = "%d{%FT%T.%f%z} %m"

[[logger]]
name = "uct"
level = "debug"
appenders = ["uct", "all"]

[[logger]]
name = "minimax"
level = "debug"
appenders = ["minimax", "all"]

[[logger]]
name = "bot"
level = "debug"
appenders = ["bot", "all"]

[[logger]]
name = "config"
level = "debug"
appenders = ["config", "all"]
