[package]
name = "oppai-iced"
version = "0.1.0"
authors = ["Evgeny Kurnevsky <kurnevsky@gmail.com>"]
license = "AGPL-3.0+"
description = "Open Points Artificial Intelligence"
edition = "2018"

[dependencies]
iced = { version = "0.2", features = [ "canvas" ] }
rand = { version = "0.7", features = [ "small_rng" ] }
clap = "2.33"
rfd = "0.1"
sgf-parser = "2.6"
oppai-field = { path = "../field" }
